`timescale 1ns/1ps
`default_nettype none

//==============================================================================
// Module: ad9226_stage1_driver
//
// Purpose:
//   1. Receive two 60 MHz clocks generated by clk_wiz_0 in the Vivado BD.
//   2. Forward the 0-degree clock to the AD9226 through an ODDR.
//   3. Capture the 12-bit ADC bus with the 180-degree shifted clock.
//   4. Optionally undo the bitwise inversion used by the referenced ADC board.
//   5. Convert straight/offset binary to signed two's complement.
//   6. Remove the ADC DC offset with a first-order IIR estimator.
//   7. Scale the 12-bit signed result to the 14-bit input used by
//      ddc_stage1_pl2_top.
//
// Direct connection to the project stage-1 module:
//   adc_data       -> ddc_stage1_pl2_top/adc_data
//   adc_valid      -> ddc_stage1_pl2_top/adc_valid
//   clk_60m_core   -> ddc_stage1_pl2_top/aclk
//   core_aresetn   -> ddc_stage1_pl2_top/aresetn
//
// BD Clock Wizard requirements:
//   clk_out1 = 60 MHz, 0 degrees
//   clk_out2 = 60 MHz, 180 degrees
//   locked   = enabled
//
// BD connections:
//   clk_wiz_0/clk_out1 -> clk_60m_adc
//   clk_wiz_0/clk_out2 -> clk_60m_sample
//   clk_wiz_0/locked   -> clk_locked
//
// IMPORTANT:
//   clk_wiz_0 is intentionally NOT instantiated in this RTL module. It must be
//   instantiated and configured in the Vivado Block Design.
//==============================================================================

module ad9226_stage1_driver #(
    // The supplied reference design inverts all 12 input bits because its
    // ADC module/front end reverses the sampled waveform polarity.
    // Set this parameter to 0 if an ILA shows about 12'h800 at zero input
    // instead of about 12'h7FF.
    parameter integer INVERT_ADC_BITS  = 1,

    // IIR DC estimator:
    //   dc_estimate[k+1] = dc_estimate[k]
    //                    + (x[k] - dc_estimate[k]) / 2^DC_FILTER_SHIFT
    // The default value 8 gives a time constant of roughly 256 samples.
    parameter integer DC_FILTER_SHIFT = 8,

    // A 12-bit ADC only contains 12 bits of information. Left shifting by
    // two does not create resolution, but maps its full-scale signed range
    // (-2048...+2047) onto the 14-bit DDC interface
    // (-8192...+8188). Valid settings for this project are 0, 1, or 2.
    parameter integer OUTPUT_LEFT_SHIFT = 2
) (
    // Clocks and lock status supplied by clk_wiz_0 in the Vivado BD.
    // 0°时钟，仅用于产生AD9226物理采样时钟
    (* X_INTERFACE_INFO =
       "xilinx.com:signal:clock:1.0 CLK_ADC CLK" *)
    (* X_INTERFACE_PARAMETER =
       "XIL_INTERFACENAME CLK_ADC, FREQ_HZ 60000000, FREQ_TOLERANCE_HZ 0" *)
    input  wire                         clk_60m_adc,
    
    
    // 180°时钟，ADC采集及算法处理时钟
    (* X_INTERFACE_INFO =
       "xilinx.com:signal:clock:1.0 CLK_SAMPLE CLK" *)
    (* X_INTERFACE_PARAMETER =
       "XIL_INTERFACENAME CLK_SAMPLE, ASSOCIATED_RESET resetn, FREQ_HZ 60000000, FREQ_TOLERANCE_HZ 0" *)
    input  wire                         clk_60m_sample,
    
    input  wire                         clk_locked,

    // 明确指定为低有效，并与CLK_SAMPLE关联
    (* X_INTERFACE_INFO =
       "xilinx.com:signal:reset:1.0 RESETN RST" *)
    (* X_INTERFACE_PARAMETER =
       "XIL_INTERFACENAME RESETN, POLARITY ACTIVE_LOW" *)
    input wire resetn,

    // Physical AD9226 interface.
    // 输出给AD9226引脚，不与resetn关联
    (* X_INTERFACE_INFO =
       "xilinx.com:signal:clock:1.0 AD_CLK CLK" *)
    (* X_INTERFACE_PARAMETER =
       "XIL_INTERFACENAME AD_CLK, FREQ_HZ 60000000, FREQ_TOLERANCE_HZ 0" *)
    output wire ad_clk,
    
    input  wire [11:0]                  ad_data_in,
    input  wire                         ad_otr_in,

    // Project stage-1 interface: signed 14-bit, continuous samples.
    output wire signed [13:0]           adc_data,
    output wire                         adc_valid,
    output wire                         adc_otr,

    // The downstream DDC must use this clock and reset together.
    // clk_60m_core is the 180-degree sampling clock, not clk_out1.
    output wire                         clk_60m_core,
    output wire                         core_aresetn,

    // Debug output; recommended for an ILA or an external status pin.
    output wire                         locked_debug
);

    //--------------------------------------------------------------------------
    // 1. ADC clock forwarding
    //--------------------------------------------------------------------------
    // Forward a clean 60 MHz clock through an output DDR register.
    // D1=1 and D2=0 reproduce the clock at Q while keeping the clock path
    // inside the dedicated FPGA clock/output resources.
    ODDR #(
        .DDR_CLK_EDGE ("OPPOSITE_EDGE"),
        .INIT         (1'b0),
        .SRTYPE       ("SYNC")
    ) u_oddr_ad_clk (
        .Q  (ad_clk),
        .C  (clk_60m_adc),
        .CE (1'b1),
        .D1 (1'b1),
        .D2 (1'b0),
        .R  (~clk_locked),
        .S  (1'b0)
    );

    //--------------------------------------------------------------------------
    // 2. Reset release synchronization in the sampling clock domain
    //--------------------------------------------------------------------------
    wire reset_async_n;
    reg  [1:0] reset_sync;

    assign reset_async_n = resetn & clk_locked;

    // Assertion is asynchronous so loss of MMCM lock immediately resets the
    // datapath. Release passes through two flip-flops to avoid metastability.
    always @(posedge clk_60m_sample or negedge reset_async_n) begin
        if (!reset_async_n)
            reset_sync <= 2'b00;
        else
            reset_sync <= {reset_sync[0], 1'b1};
    end

    assign core_aresetn = reset_sync[1];

    //--------------------------------------------------------------------------
    // 3. ADC capture, coding conversion, DC removal, and width adaptation
    //--------------------------------------------------------------------------
    ad9226_data_path #(
        .INVERT_ADC_BITS   (INVERT_ADC_BITS),
        .DC_FILTER_SHIFT   (DC_FILTER_SHIFT),
        .OUTPUT_LEFT_SHIFT (OUTPUT_LEFT_SHIFT)
    ) u_ad9226_data_path (
        .clk         (clk_60m_sample),
        .aresetn     (core_aresetn),
        .ad_data_in  (ad_data_in),
        .ad_otr_in   (ad_otr_in),
        .adc_data    (adc_data),
        .adc_valid   (adc_valid),
        .adc_otr     (adc_otr)
    );

    // Data is registered on clk_60m_sample, so the DDC is intentionally placed
    // in the same clock domain. clk_60m_adc is used only for the forwarded ADC
    // clock and must not clock the downstream DDC.
    assign clk_60m_core = clk_60m_sample;
    assign locked_debug = clk_locked;

endmodule


//==============================================================================
// Module: ad9226_data_path
//
// Pure RTL datapath separated from the Clock Wizard and ODDR so its numeric
// behavior can be simulated without Xilinx primitive models.
//==============================================================================

module ad9226_data_path #(
    parameter integer INVERT_ADC_BITS   = 1,
    parameter integer DC_FILTER_SHIFT   = 8,
    parameter integer OUTPUT_LEFT_SHIFT = 2
) (
    input  wire                         clk,
    input  wire                         aresetn,
    input  wire [11:0]                  ad_data_in,
    input  wire                         ad_otr_in,

    output wire signed [13:0]           adc_data,
    output wire                         adc_valid,
    output wire                         adc_otr
);

    localparam integer DC_ACC_WIDTH = 12 + DC_FILTER_SHIFT;

    //--------------------------------------------------------------------------
    // Stage A: capture the physical input bus close to the FPGA I/O pins
    //--------------------------------------------------------------------------
    (* IOB = "TRUE" *) reg [11:0] ad_data_capture;
    (* IOB = "TRUE" *) reg        ad_otr_capture;
    reg                           capture_valid;

    always @(posedge clk or negedge aresetn) begin
        if (!aresetn) begin
            ad_data_capture <= 12'd0;
            ad_otr_capture  <= 1'b0;
            capture_valid   <= 1'b0;
        end
        else begin
            ad_data_capture <= ad_data_in;
            ad_otr_capture  <= ad_otr_in;
            capture_valid   <= 1'b1;
        end
    end

    //--------------------------------------------------------------------------
    // Stage B: restore board polarity and convert offset binary to two's
    // complement. For offset binary, only the MSB is inverted.
    //--------------------------------------------------------------------------
    wire [11:0] ad_data_polarity_corrected;

    generate
        if (INVERT_ADC_BITS != 0) begin : g_invert_adc_bits
            assign ad_data_polarity_corrected = ~ad_data_capture;
        end
        else begin : g_keep_adc_bits
            assign ad_data_polarity_corrected = ad_data_capture;
        end
    endgenerate

    wire signed [11:0] ad_data_twos_complement;
    assign ad_data_twos_complement = {
        ~ad_data_polarity_corrected[11],
         ad_data_polarity_corrected[10:0]
    };

    //--------------------------------------------------------------------------
    // Stage C: estimate and remove the ADC DC component
    //--------------------------------------------------------------------------
    reg signed [DC_ACC_WIDTH-1:0] dc_accumulator;
    reg signed [11:0]             data_dc_removed;
    reg                           valid_out_reg;
    reg                           otr_out_reg;

    wire signed [DC_ACC_WIDTH-1:0] sample_extended;
    wire signed [DC_ACC_WIDTH-1:0] dc_estimate;
    wire signed [DC_ACC_WIDTH:0]   dc_error_wide;
    wire signed [DC_ACC_WIDTH:0]   dc_next_wide;

    assign sample_extended = {
        {(DC_ACC_WIDTH-12){ad_data_twos_complement[11]}},
        ad_data_twos_complement
    };

    assign dc_estimate = dc_accumulator >>> DC_FILTER_SHIFT;

    // One extra bit is retained for the subtraction. The difference of two
    // signed 12-bit quantities may require 13 bits.
    assign dc_error_wide =
        $signed({sample_extended[DC_ACC_WIDTH-1], sample_extended}) -
        $signed({dc_estimate[DC_ACC_WIDTH-1], dc_estimate});

    // dc_accumulator stores the estimate with DC_FILTER_SHIFT fractional bits.
    // At equilibrium, dc_accumulator / 2^shift equals the input DC value.
    assign dc_next_wide =
        $signed({dc_accumulator[DC_ACC_WIDTH-1], dc_accumulator}) +
        $signed({sample_extended[DC_ACC_WIDTH-1], sample_extended}) -
        $signed({dc_estimate[DC_ACC_WIDTH-1], dc_estimate});

    always @(posedge clk or negedge aresetn) begin
        if (!aresetn) begin
            dc_accumulator <= {DC_ACC_WIDTH{1'b0}};
            data_dc_removed <= 12'sd0;
            valid_out_reg   <= 1'b0;
            otr_out_reg     <= 1'b0;
        end
        else begin
            valid_out_reg <= capture_valid;

            if (capture_valid) begin
                dc_accumulator <= dc_next_wide[DC_ACC_WIDTH-1:0];
                otr_out_reg    <= ad_otr_capture;

                // Saturation avoids wraparound when the instantaneous sample
                // and the current DC estimate have opposite extreme signs.
                if (dc_error_wide > 2047)
                    data_dc_removed <= 12'sd2047;
                else if (dc_error_wide < -2048)
                    data_dc_removed <= -12'sd2048;
                else
                    data_dc_removed <= dc_error_wide[11:0];
            end
            else begin
                data_dc_removed <= 12'sd0;
                otr_out_reg     <= 1'b0;
            end
        end
    end

    //--------------------------------------------------------------------------
    // Stage D: adapt 12 signed bits to the project's 14-bit DDC input
    //--------------------------------------------------------------------------
    wire signed [13:0] data_sign_extended;
    wire signed [13:0] data_scaled_to_14bit;

    assign data_sign_extended =
        {{2{data_dc_removed[11]}}, data_dc_removed};

    // The left operand is explicitly 14 bits before shifting, preventing the
    // truncation that would occur if a 12-bit value were shifted first.
    assign data_scaled_to_14bit =
        data_sign_extended <<< OUTPUT_LEFT_SHIFT;

    assign adc_data  = data_scaled_to_14bit;
    assign adc_valid = valid_out_reg;
    assign adc_otr   = otr_out_reg;

endmodule

`default_nettype wire
