# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Toph Beifong/Desktop/2023_step2_by_ygw_v4/2023_step2_by_ygw.srcs/sources_1/bd/design_1/ip/design_1_demod_pool_core_bpsk_0_0/design_1_demod_pool_core_bpsk_0_0.xci
# IP: The module: 'design_1_demod_pool_core_bpsk_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/Toph Beifong/Desktop/2023_step2_by_ygw_v4/2023_step2_by_ygw.srcs/sources_1/ip/cordic_translate_0/cordic_translate_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_translate_0 || ORIG_REF_NAME==cordic_translate_0} -quiet] -quiet

# XDC: c:/Users/Toph Beifong/Desktop/2023_step2_by_ygw_v4/2023_step2_by_ygw.srcs/sources_1/bd/design_1/ip/design_1_demod_pool_core_bpsk_0_0/design_1_demod_pool_core_bpsk_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_demod_pool_core_bpsk_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/Toph Beifong/Desktop/2023_step2_by_ygw_v4/2023_step2_by_ygw.srcs/sources_1/bd/design_1/ip/design_1_demod_pool_core_bpsk_0_0/design_1_demod_pool_core_bpsk_0_0.xci
# IP: The module: 'design_1_demod_pool_core_bpsk_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/Toph Beifong/Desktop/2023_step2_by_ygw_v4/2023_step2_by_ygw.srcs/sources_1/ip/cordic_translate_0/cordic_translate_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_translate_0 || ORIG_REF_NAME==cordic_translate_0} -quiet] -quiet

# XDC: c:/Users/Toph Beifong/Desktop/2023_step2_by_ygw_v4/2023_step2_by_ygw.srcs/sources_1/bd/design_1/ip/design_1_demod_pool_core_bpsk_0_0/design_1_demod_pool_core_bpsk_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_demod_pool_core_bpsk_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
