###############################################################################
# AD9226 12-bit parallel ADC interface constraints
#
# Target design:
#   ad_clk_0       : FPGA -> AD9226 sampling clock, 60 MHz
#   adc_db_0[11:0] : AD9226 -> FPGA data bus
#   adc_otr_0      : AD9226 -> FPGA out-of-range flag
#
# Clock architecture used by the RTL/BD:
#   clk_wiz_0/clk_out1 = 60 MHz,   0 deg -> ODDR -> ad_clk_0
#   clk_wiz_0/clk_out2 = 60 MHz, 180 deg -> ADC input registers
#
# IMPORTANT:
#   1. Do not use create_clock on ad_clk_0. It is an FPGA output, not an
#      independent input clock.
#   2. Do not declare clk_out1 and clk_out2 asynchronous. They are related
#      outputs of the same Clock Wizard.
#   3. The package-pin mapping below is supplied by the board wiring and must
#      be checked against the actual schematic/header connection.
###############################################################################

# -----------------------------------------------------------------------------
# 1. Package pins
# -----------------------------------------------------------------------------

set_property PACKAGE_PIN Y7 [get_ports ad_clk_0]

set_property PACKAGE_PIN U5  [get_ports {adc_db_0[11]}]
set_property PACKAGE_PIN U7  [get_ports {adc_db_0[10]}]
set_property PACKAGE_PIN V7  [get_ports {adc_db_0[9]}]
set_property PACKAGE_PIN V8  [get_ports {adc_db_0[8]}]
set_property PACKAGE_PIN W8  [get_ports {adc_db_0[7]}]
set_property PACKAGE_PIN U8  [get_ports {adc_db_0[6]}]
set_property PACKAGE_PIN U9  [get_ports {adc_db_0[5]}]
set_property PACKAGE_PIN T9  [get_ports {adc_db_0[4]}]
set_property PACKAGE_PIN U10 [get_ports {adc_db_0[3]}]
set_property PACKAGE_PIN V6  [get_ports {adc_db_0[2]}]
set_property PACKAGE_PIN W6  [get_ports {adc_db_0[1]}]
set_property PACKAGE_PIN Y6  [get_ports {adc_db_0[0]}]

set_property PACKAGE_PIN T5 [get_ports adc_otr_0]

# -----------------------------------------------------------------------------
# 2. Electrical I/O properties
# -----------------------------------------------------------------------------

set_property IOSTANDARD LVCMOS33 [get_ports ad_clk_0]
set_property IOSTANDARD LVCMOS33 [get_ports {adc_db_0[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports adc_otr_0]

# The AD9226 clock is a 60 MHz single-ended output. FAST slew helps preserve
# the sampling edge; 8 mA is normally sufficient for one local CMOS clock load.
# If the measured clock rings, add/adjust a source-series resistor on the PCB
# rather than increasing DRIVE blindly.
set_property DRIVE 8   [get_ports ad_clk_0]
set_property SLEW FAST [get_ports ad_clk_0]

# -----------------------------------------------------------------------------
# 3. Forwarded-clock definition
# -----------------------------------------------------------------------------

# The ODDR instance name comes from ad9226_stage1_driver.v. The hierarchy
# pattern allows for the BD wrapper levels generated by Vivado.
#
# This file intentionally contains no Tcl if/else/puts statements. Those
# commands are not accepted by Vivado's XDC constraint reader.
create_generated_clock \
    -name adc_clk_fwd \
    -source [get_pins -hierarchical \
        -filter {NAME =~ *ad9226_stage1_driver_0*u_oddr_ad_clk/C}] \
    -divide_by 1 \
    [get_ports ad_clk_0]

# -----------------------------------------------------------------------------
# 4. ADC data input timing
# -----------------------------------------------------------------------------

# AD9226 datasheet switching specification at DRVDD = 3 V:
#   clock-to-output delay tOD(min) = 3.5 ns
#   clock-to-output delay tOD(max) = 7.0 ns
#
# These values currently assume 0 ns additional PCB clock/data skew. Replace
# 3.5 and 7.0 with board-adjusted early/late values when trace-delay or
# measurement data are available.
set_input_delay \
    -clock [get_clocks adc_clk_fwd] \
    -min 3.5 \
    [get_ports {adc_db_0[*] adc_otr_0}]

set_input_delay \
    -clock [get_clocks adc_clk_fwd] \
    -max 7.0 \
    [get_ports {adc_db_0[*] adc_otr_0}]

###############################################################################
# End of file
###############################################################################
