#ifndef PS_UPGRADE_BPSK_BRAM_MAP_H_
#define PS_UPGRADE_BPSK_BRAM_MAP_H_

#include <stdint.h>

#define PL_FEATURE_SEQUENCE_WORD             0U
#define PL_FEATURE_VAR_MAG_LOW_WORD          1U
#define PL_FEATURE_VAR_MAG_HIGH_WORD         2U
#define PL_FEATURE_VAR_FREQ_LOW_WORD         3U
#define PL_FEATURE_VAR_FREQ_HIGH_WORD        4U
#define PL_FEATURE_MEAN_MAG_WORD             5U
#define PL_FEATURE_MEAN_FREQ_WORD            6U
#define PL_FEATURE_PSK_WORD                  7U
#define PL_FEATURE_HIST_MAG_FIRST_WORD       8U
#define PL_FEATURE_HIST_FREQ_FIRST_WORD     24U
#define PL_FEATURE_BPSK_STATUS_WORD         40U
#define PL_FEATURE_BPSK_BIT_COUNT_WORD      41U
#define PL_FEATURE_BPSK_BITS_FIRST_WORD     42U
#define PL_FEATURE_BPSK_DEBUG_WORD          46U
#define PL_FEATURE_LAST_WORD                46U

#define PL_FEATURE_HISTOGRAM_BINS           16U
#define PL_FEATURE_BPSK_BIT_WORDS            4U
#define PL_FEATURE_BPSK_MAX_BITS           128U
#define PL_FEATURE_FRAME_SAMPLES          8192U

#define PL_FEATURE_WORD_OFFSET(word_index) ((uint32_t)(word_index) << 2)

#define PL_PSK_FLAG_MASK                    0x80000000U
#define PL_PSK_SPIKE_COUNT_MASK             0x7FFFFFFFU

#define PL_BPSK_STATUS_CARRIER_LOCKED_MASK  0x00000001U
#define PL_BPSK_STATUS_TIMING_LOCKED_MASK   0x00000002U
#define PL_BPSK_STATUS_RATE_CODE_MASK       0x0000000CU
#define PL_BPSK_STATUS_RATE_CODE_SHIFT      2U
#define PL_BPSK_STATUS_FRAME_OVERFLOW_MASK  0x00000010U

#define PL_BPSK_DEBUG_FRAME_OVERFLOW_MASK   0x00000001U
#define PL_BPSK_DEBUG_OVERFLOW_STICKY_MASK  0x00000002U
#define PL_BPSK_DEBUG_OVERRUN_STICKY_MASK   0x00000004U
#define PL_BPSK_DEBUG_DROPPED_BITS_MASK     0x0000FF00U
#define PL_BPSK_DEBUG_DROPPED_BITS_SHIFT    8U
#define PL_BPSK_DEBUG_OVERRUN_COUNT_MASK    0xFFFF0000U
#define PL_BPSK_DEBUG_OVERRUN_COUNT_SHIFT  16U

#endif /* PS_UPGRADE_BPSK_BRAM_MAP_H_ */
